### ISSUE TITLE
ECHAM6 HIST ERA5-nudged simulation: Missing forcing files after year 2015

### ISSUE THREAD

**Issue by QinggangGao** [esm-tools/esm_tools#1064]
Dear Team

I plan to run an ERA5-nudged HIST simulation using ECHAM6 from 2013 to 2022. But it failed at the beginning because of missing forcing files. Note that the simulation succeeded if I ran it for the year 2000. The simulation also succeeded when I ran a HIST simulation using ECHAM6 and dataset r0008 without ERA5-nudged.

esm_tools version: 6.23.3
echam version: 6.3.05p2-wiso
runscripts: `/albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/test/scripts/nudged_echam6_1m.yaml`
exp folder: `/albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/test`
echam: dataset: r0007
log file: `/albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/test/log/test_echam_compute_20130101-20130131_6730712.log`
error message: IO_open failed on: landuseTransitions.2013.nc
output while run the script:

> WARNING: File not found: /albedo/pool/ECHAM6/input/r0007/T63/ozone/T63_ozone_HIST_2015.nc
> WARNING: File not found: /albedo/pool/ECHAM6/input/r0007/T63/volcano_aerosols/strat_aerosol_sw_T63_2015.nc
> WARNING: File not found: /albedo/pool/ECHAM6/input/r0007/T63/volcano_aerosols/strat_aerosol_ir_T63_2015.nc
> WARNING: File not found: /albedo/work/projects/p_pool_jsbach3/T63/New_Hampshire_LCC/hist/LUH_transitions_T63_2013.nc
> WARNING: File not found: /albedo/work/projects/p_pool_jsbach3/T63/New_Hampshire_LCC/hist/LUH_transitions_T63_2012.nc
> WARNING: File not found: /albedo/work/projects/p_pool_jsbach3/T63/New_Hampshire_LCC/hist/LUH_transitions_T63_2014.nc
> WARNING: File not found: /albedo/work/projects/p_pool_jsbach3/T63/New_Hampshire_LCC/hist/LUH_harvest_T63_2013.nc
> WARNING: File not found: /albedo/work/projects/p_pool_jsbach3/T63/New_Hampshire_LCC/hist/LUH_harvest_T63_2012.nc
> WARNING: File not found: /albedo/work/projects/p_pool_jsbach3/T63/New_Hampshire_LCC/hist/LUH_harvest_T63_2014.nc

**Comment by nwieters** [comment]
Hi @l975421700 ,
sorry for the late reply. Is this still an issue for you?

I find that there are no files available in the folder /albedo/work/projects/p_pool_jsbach3/T63/New_Hampshire_LCC/hist/ for years >2010. Should there be some? I don't know who is responsible for this pool directory.

Hi @pgierz , I am asking you because you are named as the owner of this pool dir. Do you know who to contact about the content of this pool directory on Albedo?

Thank you.

**Comment by nwieters** [comment]
Hi @christian-stepanek ,
are you the person to contact for this specific pool directory  `/albedo/work/projects/p_pool_jsbach3`?
It seems that @l975421700 is missing certain files in this pool dir.
Thank you.

**Comment by christian-stepanek** [comment]
Hi @nwieters @l975421700. I do not think that this is a pool problem. There are no ozone forcing files available beyond the year 2014. Rather, one needs to tell esm-tools to reuse the newest ozone forcing also for the years beyond 2014. @l975421700 actually had a very similar issue https://github.com/esm-tools/esm_tools/issues/1060 that got closed (and I assume solved) in the mean time.

**Comment by nwieters** [comment]
Thank you @christian-stepanek for clarifying the availability of these data files and pointing to the related issue.

@l975421700 I will have a look into the jsbach.datasets.yaml and check if there is still something missing like for issue #1060.

**Comment by nwieters** [comment]
Hi @l975421700 ,

I can't really reproduce the error you get since I get other issues when setting up a test run like yours. Since the experiment you mentioned above is not there anymore, I don't know how you setup your experiment.

If so, please provide a path to another experiment that runs into the same issue. 

Please also reply if this is no longer an issue. If this is the case, please close this issue or let me know so I can close it for you.

Thank you very much and I look forward to your replay.

**Comment by QinggangGao** [comment]
Dear Nadine

Thank you. It is no longer an issue for me. I will close it.

Regards, Qinggang
