### ISSUE TITLE
plugins re-installed upon every run of esm_master

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_tools#247]
**Describe the bug**
If you have a dependency for a plugin coded into your components setup (e.g. `oifs.yaml`)
```
required_plugins:
    - "git+https://github.com/esm-tools-plugins/preprocess"
```
`esm_master` will re-install it every time you run it.
**To Reproduce**
`esm_master comp-oifs-v43r3-v1 -c`
`esm_master comp-oifs-v43r3-v1 -c`

**Expected behavior**
esm_master should only re-install the plugin if it is not installed or outdated.
Current workaround it to comment the `required_plugins` section after the plugin has been installed.

**System (please complete the following information):**
 - Supercomputer: does not matter
 - Version: latest version of all tools

**Comment by pgierz** [comment]
...that should not be happening. This bit:
https://github.com/esm-tools/esm_master/blob/7d9daac71504d95d03406d7a0155c6af87318759/esm_master/task.py#L371

just runs `pip install <plugin>` where `plugin` is one of the things you put in `required_plugins`. Since there is no `-U` option given to the pip call, it should not "reinstall", but just say "dependency already satisfied". It should take a minimal amount of time to check that.

If you want, I can make pip quiet, but automatically figuring out which plugins are already there and which are not might be a bigger job, I'd need to look into it.

**Comment by pgierz** [comment]
OK, I know now why that is happening. As soon as pip detects that you give `git+...` it **needs** to redownload everything, as it has no way of consistently caching the result. If we published our packages on PyPI that might circumvent that.

**Comment by mandresm** [comment]
This should be solved now so I close it.
