### ISSUE TITLE
date: argument list too long

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#263]
Gregor reported an issue that seems to be connected to logging of the experiment run times.

The sad file contains a command (similar):

```shell
echo $(date +%c) : compute 322 2321-01-01T00:00:00 27295270 - start >> /work/ba0989/a270077/PalModII/phase_space_analysis/experiments//LGM_Ctrl_001/log//LGM_Ctrl_001_awiesm.log
```

In some cases (no clear pattern found yet), this yields the following error:

```
/var/log/slurm/spool_slurmd//job27242157/slurm_script: line 78: /bin/date: Argument list too long
/var/log/slurm/spool_slurmd//job27242157/slurm_script: line 82: /work/ba0989/a270077/PalModII/phase_space_analysis/experiments/LGM_Ctrl_001/.venv_esmtools/bin/esm_runscripts: Argument list too long
/var/log/slurm/spool_slurmd//job27242157/slurm_script: line 79: /usr/bin/srun: Argument list too long
```

Could it be that the `:` character is breaking things, as it is shell for "do nothing" (i.e. `pass`)? If yes, why does this only happen sometimes? In any case, would the following help (note the double quotes):
```shell
echo "$(date +%c) : compute 322 2321-01-01T00:00:00 27295270 - start" >> /work/ba0989/a270077/PalModII/phase_space_analysis/experiments//LGM_Ctrl_001/log//LGM_Ctrl_001_awiesm.log
```

This *might* be linked to quota issues, see in particular the second answer [here](https://stackoverflow.com/questions/26268969/argument-list-too-long-for-every-command)

Some examples of where this problem occurs:

* `/work/ba0989/a270077/PalModII/phase_space_analysis/experiments/LGM_Ctrl_001/scripts/LGM_Ctrl_001_compute_23210101-23211231_27242157.log`
* `/work/ba0989/a270083/MODELLE/experiments/AWIESM2.1/CFon_HYon/scripts/CFon_HYon_compute_23210101-23211231_27263748.log`

**Comment by denizural** [comment]
Hi @pgierz,

I looked at the errors and have some solution candidates. I checked the `sad ` files, not the ones related to these log files since they don't exist but the other ones.

It is really strange to get these "`Argument list too long`" errors. Usually these happen when the number of arguments exceed the system defined maximum and using xargs is the fix.

What I would start with is changing that echo statement to something more robust. Eg.

In `esm_runscripts/batch_system.py`, in function `get_run_commands()`, I would replace

`commands.append(f'echo "{line}" >> {config["general"]["experiment_log_file"]}')`

Here I added surrounding double quotes so that everything is treated a string.

So that instead of printing 

`echo $(date +%c) : compute 693 2692-01-01T00:00:00 27262911 - start >> foo.log`

it will print 

`echo "$(date +%c) : compute 693 2692-01-01T00:00:00 27262911 - start " >> foo.log`

Using `printf `instead of `echo `(with the additon of `\n`) can also be used since printf is more robust than echo. Here is a nice read: 
https://www.in-ulm.de/~mascheck/various/echo+printf/

I don't know if it is helpful but maybe for debug purposes you can also give the command
`getconf ARG_MAX`
before it reaches the call to date. Maybe here :grinning:

```
if config["general"].get("funny_comment", True):
    extras.append("# 3...2...1...Liftoff!")
```

The overview of the function call tree is something like this:

```call to sim_objects
    call to write_simple_runscript
    def write_simple_runscript(config):                                    # batch_system.py, line 173
        commands = batch_system.get_run_commands(config)                   # batch_system.py, line 185
        def get_run_commands(config)                                       # batch_system.py, line 136
            line = helpers.assemble_log_message("  .... -start")           # batch_system.py, line 140
            def assemble_log_message()                                     # helpers.py, line 124
                timestampStr = "$(date +" + strftime_str + ")"             # helpers.py, line 134  
                line = timestampStr + " : " + message_sep.join(message)    # helpers.py, line 138
            commands.append("echo ...")
```

I speculate that depending on the compute node and shell (`bash `vs `zsh`) on Mistral there might be differences. I tried to replicate it but was not successful so let's try the ones above and hope that it solves.

The trailing '`Argument list too long`' errors are really strange. I hope this solution will also solve them all

**Comment by pgierz** [comment]
This never popped up again, who knows what that was. Please re-open if we need, but closing to prepare for the release.
