### ISSUE TITLE
arrays in add_namelist_changes

### ISSUE THREAD

**Issue by joakimkjellsson** [esm-tools/esm_tools#264]
Happy New Year all

I'm trying to add some new functionality to OpenIFS in ESM-Tools v5, and I need to be able to add an array as a namelist value. 
For example, what I've done now in oifs.yaml is:

```
choose_pextra:
	1:
                add_namelist_changes:
                        fort.4:
                               	NAEPHY:
                                        LBUD23: ".true."
                                NAMDPHY:
                                        NVEXTR: 25
					NCEXTR: ${nlev}
                                NAMPHYDS:
                                        NVEXTRAGB: 91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,\
115,
                                NAMFPC:
                                        NFP3DFS: 25
					MFP3DFS: 91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,11\
5,
```

NVEXTRAGB is an integer array, so the values above should be given as 25 integers. 
However, when the namelist is assembled by ESM-Tools, I end up with this: 

```
&NAMPHYDS
    NVEXTRAGB = '91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,'
/
```

So it has interpreted this as one long string rather than an integer array. 
I don't know if this is a limitation in ESM-Tools or the f90nml functions it uses. 
I could of course create a new namelist template with this filled in, but it would quickly get out of hand with the different settings of NVEXTRAGB I might want to use. 

Has anyone managed to do something like this before, or am I on uncharted waters here? 
Does anyone have some suggestion on how to give arrays in namelists? 

Many thanks for any help!

Cheers
Joakim 

PS: My versions: 
esm-tools: 5.0.2
esm-runscripts: 5.0.3

**Comment by pgierz** [comment]
Hi Joakim,

f90nml can definitely handle arrays, so it's probably our parser that's causing you headaches. Before I dive deeply into the code, can you check something? Does it work if you make `NVEXTRAGB` into a list? Just surround it with square brackets. Fingers crossed that already helps, if not, we will look into it...

All the best,
Paul

**Comment by denizural** [comment]
Hi @joakimkjellsson,

I was actually looking at it. Could you also please provide a runscript so that I can replicate it.

Cheers,
Deniz

**Comment by denizural** [comment]
Dear @joakimkjellsson and @pgierz,

Problem is solved. Here is the trick. I worked it on ECHAM and I am sure the OIFS will also run just as fine. 

In my sample runscript I added:

```
echam:
    # ... stuff ...
    add_namelist_changes:
        namelist.echam:
            foo:
                bar: 666
                NVEXTRAGB:
                    [91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115]
```
    
For debug purposes I also printed the data inside the namelist.py

```
for key in list(change_entries):
    print(key)
    print(change_entries[key])
    print(type(change_entries[key]))
    if isinstance(change_entries[key], list):
        print(type(change_entries[key][0]))
    print("=============================")
```

When the esm_runscript runs it prints 

```
=============================
bar
666
<class 'int'>
=============================
NVEXTRAGB
[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]
<class 'list'>
<class 'int'>
=============================
```
and in the verbose mode the namelist section is printed as 

```
&foo
    bar = 666
    nvextragb = 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103,
                104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115
/
```

The important trick is **NOT** using the FORTRAN line continuation character '\\'. Good ol' FORTRAN has an infamous _maximum character length_ issue. Actual length depends on the compiler (132 or more). This is why we need to break the code with '\\'. In the appendix I will show a demo Fortran code to test the length issue. However, there is another caveat here. When, I use a back slash like  

```
add_namelist_changes:
    namelist.echam:
        foo:
            bar: 666
            NVEXTRAGB:
                [91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,\
                115]
```

`NVEXTRAGB `is still a `<class 'list'>` but the output is 

```
&foo
    bar = 666
    nvextragb = 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103,
                104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, '\ 115'
/
```

Remember that the Python lists are actually linked lists and not arrays. Therefore, they don't necessarily contain homogeneous data like arrays. Here the final all but last elements are `int `but the final one `'\ 115'` is a `str`.

This is actually a problem I mentioned in one of our group meetings as @pgierz can remember. Since the solution is rather simple, I think it is best to leave it like this instead of modifying the parser. I will make note of this in the documentation. 

### APPENDIX:
**Testing the maximum length in namelist input**

**FORTRAN code (read_nml.f90):**

```
program read_nml
    integer            :: i
    integer            :: j
    character(len=60) :: str
    integer, dimension(500) :: my_array
    namelist /vars/ i, j, str, my_array

    open(unit=1, file='joachim.nml')
    read(unit=1, nml=vars)

    print *, i
    print *, j
    print *, str
    print *, "---------------------------------------"

    print *, "contents of the namelist: "
    write (nml=vars, unit=6)
end program read_nml
```

**Sample namelist input (joachim.nml):**

```
&vars
    i=5,
    j=17,
    str='Hello, World!',
    ! I just truncate is here but this is a very LONG line
    my_array=0,1,2,3,4,5,6,7,8,9,10,11, ... 498,499
/

```
`gfortran read_nml.f90 -o read_nml
`
`./read_nml
`           
```
          5
          17
 Hello, World!
 ---------------------------------------
 contents of the namelist:
&VARS
 I=          5,
 J=         17,
 STR="Hello, World!                                               ",
 MY_ARRAY=          0,          1,          2,          3,          4,
           5,          6,          7,          8,          9,         10,
          11,         12,         13,         14,         15,         16,
          17,         18,         19,         20,         21,         22,
          23,         24,         25,         26,         27,         28,
          ... ! bunch of stuff, again truncated
         485,        486,        487,        488,        489,        490,
         491,        492,        493,        494,        495,        496,
         497,        498,        499
```
The result shows that you don't need to put a backslash continuation in your namelist. At least my editor tells me that at column 1903 :scream: it is still fine. I also added line breaks in the array in the namelist and it is still fine. So, don't worry about esm-tools breaking the array into multiple lines.

If everyone is happy I can close the issue.

Cheers,
Deniz

**Comment by joakimkjellsson** [comment]
Hey guys
Thanks for the super-quick answer! Yes, using a list with [ ] did solve the problem. 
Phew, that saves me the effort of saving a bunch of templates! 

Have a good weekend!
/J

**Comment by denizural** [comment]
Thanks for you kind compliments Joakim. Have a nice week!
