### ISSUE TITLE
Modification of fesom2 namelist.io

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#324]
At the moment the esm_tools overwrite pretty much all changes to a namelist.io from fesom-2.0.io.yaml. Users of all kinds of climate models, including FESOM2, are used to namelists not just being templates but a control interface for simulations.

It took me an half an hour to figure out why none of my changes to the namelist.io were making it into the experiments, and that's for a user that has been using the tools for the past 4 months already. Someone that just starts out would be totally lost. I would consider this "feature" to be potentially damaging, since users might run experiments after modifying the namelist.io, thinking they get the output they need, while esm_tools is happily overwriting all of their settings. And it does so silently from a further reading, in a component, that's part of a setup, for which they are running their runscript, quite deep down. Without turning on verbose output, you don't even see any hint of it happening until you look into your work folder and wonder where your output is.

I can see that for certain namelist entries an overwrite from the esm_tools is useful, e.g. paths, timestep, turning off salinity restoring for coupled runs etc. But output configuration doesn't seem like it falls under in the "this should be automated and the controls should be hidden from plain sight" category.

I would suggest removing the fesom-2.0.io.yaml. If people want to modify the namelist.io they can do so from their runscript or setup, but to do it by default for all FESOM2 runs is unexpected.

**Comment by JanStreffing** [comment]
Maybe its better explained with a hypothetical example:

Lorenzo is currently starting on coupling Icepack in AWI-CM3. He has 3-4 Years of experience with standalone FESOM2 and it's native runscripts. He knows by heart that FESOM2 output is controlled from the namelist.io.

He starts working with esm_tools and the first thing he does with the IO, is adding his Icepack variables (thickness classes, meldponds etc.) to the namelist.io. This works as he expects, because those variables are not overwritten from the `fesom-2.0.io.yaml`, building confidence that in the esm_tools FESOM2 output is still controlled the way he learned it. Let's say he then wants to run a larger test with AWI-CM3. This time he would like to look at brine rejection as well and changes the 3D `salt` variable from yearly to daily and runs 10 years with the model. `salt` however, happens to be one of the variables that is overwritten and will only be present as yearly means.

**Comment by mandresm** [comment]
Hi @JanStreffing, how you use `namelist_changes` is ultimately up to you and the users/developers. @mathanase and I put together this `fesom-2.0.io.yaml` instead of just leaving them into her runscript, so that other users can use this feature.

If you want to remove it, please go ahead and do so (just remove the respective `further_reading` in `awicm3.yaml`). It can even go on the runscripts so @mathanase can use it from there through her runscript. I'm sorry I did not communicate those changes to you, we've been developing two people at a very fast pace and this type of conflicts are expected. Now that development pace has slow down and that you will be the main contributor of `awicm3.yaml` I would expect things to be more stable, but that will ultimately depend on the quality of the communication inside the contributors of AWICM3.

**Comment by JanStreffing** [comment]
Ah, so this is an AWI-CM3 thing! I though it is a general FESOM2 thing and might come from AWI-ESM where certain FESOM2 output is always needed for PISM coupling. Ok yeah let's remove it. As explained above, I think this feature is dangerous to those that don't know it's there.

If Marylou want's to control output in this way it can go as further reading in her runscript, or she could use a different namelist.io template.

**Comment by koldunovn** [comment]
@JanStreffing I think it's a good idea to remove the output from the default `fesom-2.0.yaml`, since sane defaults should be in the namelist.io and if someone wants to modify it, it can be done in experiment configuration yaml. 

However here comes the conceptual question of ether you use namelists to control configuration (things that developers get used to), and then probably only use esm_tools to control the simulation, or you use yaml to control both configuration and simulation, where you also can set anything, and be sure that this will overwrite everything which was set before.

Mixing two approaches (modify half of the things in the namelist and another half in the yaml) in my view is a way to hell :) But I might be wrong, not having a lot of hands on experience with esm_tools yet.

**Comment by JanStreffing** [comment]
I would say that I would personally like to keep the esm_tools modifications of the namelists down to a minimum.  However, especially when it comes to dangerous switches, such as the default `surf_relax_S=1.929e-06`, some control of esm_tools over the namelists is an invaluable asset. Overwriting this by default for all AWI-CM3 simulations will save tens of thousands of nodehours and Euros, as well as many months and headaces in the long run. I can't imagine going full namelists.

Controlling the entire simulations exclusively from esm_tools on the other hand sounds like a large maintenance task because the yaml files have to follow entry by entry the frequently changing namelists of FESOM2. This might be ok for standalone end-users that do science with the same FESOM2 version for a year or two, But it does not sound reasonable for everyone that is doing development work on coupled models where FESOM2 is frequently updated.

Thus some mix of the two evolved naturally. I saw a similar thing happening in the EC-Earth community where some of the control lay in the runscript, and some in the namelist. Having pure namelist control like FESOM2 has (had?) is unusual, I think.

**Comment by koldunovn** [comment]
I would not argue against the fact that controlling simulations through the namelists is more convinient for the developers, and will stay so. However in defense of esm_tools - yaml files should only indicate changes from defaults in the namelists, so it's not that big of a burden to support them. 

At the end the namelists in your simulation folder, whether created by scripts, or modified by hand, are the ultimate truth. This is what will go to machine and this is what should somehow be checked. Maybe we need a tool, that shows all the changes in the namelists with respect to default ones. Maybe even with tips of what is dangerous in coupled and uncoupled setups. As @JanStreffing rightly put it, mistakes in the namelists can cost a lot, so having a sane diff tool could be beneficial.

**Comment by mandresm** [comment]
> Maybe we need a tool, that shows all the changes in the namelists with respect to default ones.

Such a tool can be implemented relatively fast. If you think this tool would be of great value, let's discuss and come out with a clear idea of how the output of such a tool should be, and when and where this output should be produced. Then, the development team can take care of its development.

**Comment by JanStreffing** [comment]
The feature showing all the namelist changes is part of the finished config yaml. I got more confident manipulating namelists via yaml. The overwriting of default namelist that was happening in every fesom2 simulation is no longer taking place as of release 6. I consider this issue solved.
