### ISSUE TITLE
Automation Idea

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#553]
Hello,

it's Saturday, I know. But while I wait for my father to park his car and call me back from the other side of the world, I browse GitHub...

Random idea, could be noted here before it gets forgotten:

We could find a way to have the github automatization do all the tag/bump/publish-to-pypi stuff whenever something is merged into release. The publish step is already at least partially there...

**Comment by denizural** [comment]
Well, this is a full CI/CD pipeline. I hope one day we can reach such IT maturity. The problematic step is testing. Many big IT companies have a completely working CICD practice where a new version gets deployed with a commit. I heard that Facebook rolls upto 50 versions in a day. Deploying software is not difficult but what we don't want is receiving issues that something is broken. So, rather than having a full CICD we can look for a monthly (or so) automated releases when the tests are fine.

**Comment by pgierz** [comment]
This still is broken, for some reason. It seems as if tag pushes are not triggering the CI job. However, since no one is doing `pip install`, this one will take low priority for right now.

**Comment by pgierz** [comment]
Closing as finished, we did at least most of this.
