### ISSUE TITLE
running esm_runscript -t post does not work

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_tools#557]
**Describe the bug**
If I type `esm_runscrpts -h` it lists 
```
-t TASK, --task TASK  The task to run. Choose from: prepcompute, post,
                        couple, tidy
```
However if I do (I thought I can use this to run my postprocessing scripts after changing `postprocessing: false` to `postprocessing: true`), I get an error message:
```
Traceback (most recent call last):
  File "/home/shkifmsw/.local/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-tools', 'console_scripts', 'esm_runscripts')()
  File "/home/shkifmsw/esm/esm_tools/src/esm_runscripts/cli.py", line 268, in main
    Setup()
  File "/home/shkifmsw/esm/esm_tools/src/esm_runscripts/sim_objects.py", line 90, in __call__
    resubmit.maybe_resubmit(self.config)
  File "/home/shkifmsw/esm/esm_tools/src/esm_runscripts/resubmit.py", line 152, in maybe_resubmit
    nextrun = resubmit_recursively(config, jobtype=jobtype)
  File "/home/shkifmsw/esm/esm_tools/src/esm_runscripts/resubmit.py", line 180, in resubmit_recursively
    jobtype
KeyError: 'post'
```
**To Reproduce**
run `esm_runscripts -e expo -t post my_runscript.yaml`

**Expected behavior**
Well, at least not a crash :-)

**System (please complete the following information):**
 - Supercomputer: glogin
 - Version: release 6 latest version

**Comment by mandresm** [comment]
On version 5, although not fully functional, postprocessing was a step on the recipe. But now postprocessing is something you control through the workflow manager in a more generic way: you can insert jobs after any standard esm_runscripts step, and although this is normally used to do postprocessing, you could virtually insert any type of job and name it anyway you wanted.

What I suggest here is that we enable the `--task` option to be able to submit `subjobs` (i.e. `esm_runscripts <runscript.yaml> -t echam_postprocessing`). That could be develop in conjunction with a solution to avoid #554 and make it part of the PR #556 .

Unfortunately, I have no time to look at this until next week. If someone else wants to take care of it, please go ahead :)

As a provisional solution, since your postprocessing is triggered by `tidy` you might want to use `-t tidy`.

**Comment by pgierz** [comment]
I can have a look at this. @seb-wahl I will work directly on your branch. @mandresm, I know you are busy, but I may need to spontaneously call you for some hints with the workflow manager, you are much deeper into that than I am...

**Comment by seb-wahl** [comment]
Suggestion: To be clean I would first merge my developments into release or develop and then continue with a fresh branch. Otherwise we have too many things in one branch, and I'd like to tell my folks that postprocessing is now available in release for FOCI. I don't want my users to work on feature branches that constantly change.

**Comment by mandresm** [comment]
Okay @seb-wahl , then I will merge #556 now.

**Comment by pgierz** [comment]
OK, I had branched off anyway for my fixes of the post flag, so we will just make a new PR from that.

**Comment by nwieters** [comment]
Hi @seb-wahl, @pgierz, @mandresm,
has this issue been solved already by one of the above mentioned pull requests?

**Comment by pgierz** [comment]
As far as I am aware, we do not have a "post" job (yet). This was always one of those things we wanted to include, but never really had time for. For your own notes, it might be nice to explore how easy it is to add new job-types that hook in after the compute (or tidy) job are finished. At the moment we have the workflow manager for that, which is on the list for overhauling.

**Comment by pgierz** [comment]
Em, sorry: long story short, we can close this one. If needed, please re-open.
