### ISSUE TITLE
GH project web site unavailable? www.esm-tools.net

### ISSUE THREAD

**Issue by kinow** [esm-tools/esm_tools#825]
**Describe the bug**

Learned about `esm_tools` today in a meeting, found via ddg the link to this repository, then clicked on the site, but it's showing some sort of domain parking page, I think?

**To Reproduce**

[www.esm-tools.net](https://www.esm-tools.net/)

**Expected behavior**

Maybe the project docs?

**Screenshots**
![image](https://user-images.githubusercontent.com/304786/191735966-18d74f82-8b86-4557-9de7-5c9f61f75f8e.png)

**System (please complete the following information):**
NA

**Additional context**

Thanks

**Comment by mandresm** [comment]
Dear @kinow ,

Thanks for reporting this.

The site is offline due to licensing, and it won't come back soon. However, it was out of date. You can find the useful information you need in this resources:
- https://esm-tools.readthedocs.io/en/latest/introduction.html
- https://github.com/esm-tools/workshops/tree/main/202207_AWI_ESM-Tools

**Comment by kinow** [comment]
Thanks @mandresm, maybe someone with access to the settings of this repository could change the URL to one of these two (I think the readthedocs one looks like a useful intro). Thanks!!

**Comment by mandresm** [comment]
Taken your suggestion and have added the docs page there, until we have our page back again.

**Comment by kinow** [comment]
Thanks @mandresm !
