### ISSUE TITLE
Overwrite default executable name by component version

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#841]
Bit of background: In esm_runscripts we use the name of the executable in oasis.py as the NBMODEL name:

https://github.com/esm-tools/esm_tools/blob/eb5353984fabd8e9f424074bb280ff55c51b17a9/src/esm_runscripts/oasis.py#L38

This is not really correct, as the oasis name of the model does not have to be the executable name that we use for slurm. It's a variable that each model has hard coded in it's source code. So far we got around this by just always selecting exe name = NBMODEL name.

For ECE4-F/AWI-ESM3 I am now switching to the SMHI OpenIFS git repo. For our DKRZ git repo we used the name `oifs` for both NBMODEL and for the executable. Inside the ECE4 source code they have chosen `OpenIFS` instead of oifs as the NBMODEL name. Since we can't set the NBMODEL name separately from the executable name currently, I now want to overwrite the executable name for this new model version.

I thus try to overwrite:
https://github.com/esm-tools/esm_tools/blob/9e0bccf415b0b19701e4a91a0afdbf9a7fe0b3ee/configs/components/oifs/oifs.yaml#L6
with:
https://github.com/esm-tools/esm_tools/blob/9e0bccf415b0b19701e4a91a0afdbf9a7fe0b3ee/configs/components/oifs/oifs.yaml#L114

However when I run an experiment, the final yaml file (`/p/scratch/chhb19/streffing1/runtime/awicm3-master/smhi_5/run_20000101-20000101/config/smhi_5_finished_config.yaml`) contains:
`    executable: oifs`

Am I missing something obvious?

**Comment by mandresm** [comment]
On that same yaml (`/p/scratch/chhb19/streffing1/runtime/awicm3-master/smhi_5/run_20000101-20000101/config/smhi_5_finished_config.yaml`) if you look for `version` in the `oifs` section it is `43r3`. I guess it should be `43r3-master` right? That should be triggered simply by stating `general.version: master` as the coupling file is already pointing at the correct OpenIFS version.

**Comment by JanStreffing** [comment]
I already have `general.version: master` in the run script:
```
general:
    user: !ENV ${USER}
    setup_name: "awicm3"
    version: "master"
```
We have in the past never used the 43r3- before the version. e.g. a working v3.1 runscript looks like:
```
general:
    user: !ENV ${USER}
    setup_name: "awicm3"
    version: "v3.1"
```

You think it should always by 43r3-$something?

**Comment by mandresm** [comment]
Hi Jan,

Up to now you have never needed to associate the specific version of OpenIFS to AWICM3 during run time (for compilation you did, through the `coupling` files). During run time the version was set here:
https://github.com/esm-tools/esm_tools/blob/9e0bccf415b0b19701e4a91a0afdbf9a7fe0b3ee/configs/setups/awicm3/awicm3.yaml#L87-L88
Then, in `oifs.yaml` is selected **during runtime** (yes, coupling files are not used during run time -.-):
https://github.com/esm-tools/esm_tools/blob/9e0bccf415b0b19701e4a91a0afdbf9a7fe0b3ee/configs/components/oifs/oifs.yaml#L148-L154

That means this is never reached during runtime:
https://github.com/esm-tools/esm_tools/blob/9e0bccf415b0b19701e4a91a0afdbf9a7fe0b3ee/configs/components/oifs/oifs.yaml#L110-L119
That did not matter for AWICM3 because there were no differences in the variables needed for runtime among the different 43r3 versions.

The way we do it in AWI-ESM-2 is to assign specific model versions to different versions of the coupled setup. For example, you could add `version: 43r3-master` in the version choose block of OpenIFS, and that would do:
https://github.com/esm-tools/esm_tools/blob/9e0bccf415b0b19701e4a91a0afdbf9a7fe0b3ee/configs/setups/awicm3/awicm3.yaml#L143-L166

**Comment by mandresm** [comment]
In summary, the method to select versions is not consistent between compilation and runtime. One of the many reasons we want to rewrite  esm_master, get it to use the esm_parser (as esm_runscripts does), and potentially get rid of the unnecessary coupling files. I'll open an issue, and include it in our cleanup project.

**Comment by JanStreffing** [comment]
Thanks @mandresm I tried that.

problem is that our input folders are using oifs-43r3 as a path. So do our default namelists... :/

```
WARNING: File not found: /p/project/chhb19/streffing1/input/oifs-43r3-master/TCO95L91/ICMGGaackINIT_CORE2
WARNING: File not found: /p/project/chhb19/streffing1/input/oifs-43r3-master/TCO95L91/ICMGGaackINIUA
WARNING: File not found: /p/project/chhb19/streffing1/input/oifs-43r3-master/TCO95L91/ICMSHaackINIT
WARNING: File not found: /p/project/chhb19/streffing1/input/oifs-43r3-master/TCO95L91/wam_grid_tables
WARNING: File not found: /p/project/chhb19/streffing1/input/oifs-43r3-master/TCO95L91/wam_subgrid_0
WARNING: File not found: /p/project/chhb19/streffing1/input/oifs-43r3-master/TCO95L91/wam_subgrid_1
WARNING: File not found: /p/project/chhb19/streffing1/input/oifs-43r3-master/TCO95L91/wam_subgrid_2
WARNING: File not found: /p/project/chhb19/streffing1/input/oifs-43r3-master/TCO95L91/uwavein
WARNING: File not found: /p/project/chhb19/streffing1/input/oifs-43r3-master/TCO95L91/specwavein
WARNING: File not found: /p/project/chhb19/streffing1/input/oifs-43r3-master/TCO95L91/sfcwindin
WARNING: File not found: /p/project/chhb19/streffing1/input/oifs-43r3-master/TCO95L91/cdwavein
WARNING: File not found: /p/project/chhb19/streffing1/input/oasis/cy43r3-master/TCO95-CORE2/areas.nc
WARNING: File not found: /p/project/chhb19/streffing1/input/oasis/cy43r3-master/TCO95-CORE2/masks.nc
WARNING: File not found: /p/project/chhb19/streffing1/input/oasis/cy43r3-master/TCO95-CORE2/grids.nc
WARNING: File not found: /p/project/chhb19/streffing1/model_codes/awicm3-master/bin/oifs
WARNING: File not found: /p/project/chhb19/jstreffi/esm_tools/namelists/oifs/43r3-master/awicm3/master/fort.4
WARNING: File not found: /p/project/chhb19/jstreffi/esm_tools/namelists/oifs/43r3-master/awicm3/master/wam_namelist
WARNING: File not found: /p/project/chhb19/streffing1/model_codes/awicm3-master/oasis/cf_name_table.txt

```

**Comment by mandresm** [comment]
I see. There are several ways to tackle this, the simplest one would be to add to the `general.choose_version.master` the `executable: OpenIFS`. That's not ideal because if later on it's decided that we should change the executable name, then we have to change it in two places.

A more generalized option would be to add a new variable `namelist_version` in the `oifs.yaml` and used that variable to construct the namelist's dirs, instead of the `oifs.version`. Then one could set that variable to be whatever is needed in the `choose_version` switches.

**Comment by JanStreffing** [comment]
Option 1 means I add `executable: OpenIFS`
https://github.com/esm-tools/esm_tools/blob/9e0bccf415b0b19701e4a91a0afdbf9a7fe0b3ee/configs/setups/awicm3/awicm3.yaml#L35-L41
?
That one did not work:
`- missing source: /p/project/chhb19/streffing1/model_codes/awicm3-master/bin/oifs`

I will try the second option instead.

**Comment by mandresm** [comment]
Nope, option 1 means add `executable: OpenIFS` here:
https://github.com/esm-tools/esm_tools/blob/9e0bccf415b0b19701e4a91a0afdbf9a7fe0b3ee/configs/setups/awicm3/awicm3.yaml#L143-L166

**Comment by JanStreffing** [comment]
The hotfix worked and will be used. Ty @mandresm
