### ISSUE TITLE
fesom configs namelist.config only

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#857]
**Describe the bug**
In an `awicm-1.0-recom` experiment, only the `namelist.config` is saved in the `configs/fesom` directory. All other namelists are missing.

**Expected behavior**
All namelists (of any model) should be saved.

**System (please complete the following information):**
```
version = esm_tools, version 6.17.1
branch  = release
hash    = 57ef6a69
src     = /home/a/a270073/esm/esm_tools (levante0.atos.local)
```

**Comment by mandresm** [comment]
Hi Chris,

Can you provide a path to the experiment folder?

**Comment by chrisdane** [comment]
```
/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/esm-piControl_wout_talk_rest2
```

**Comment by mandresm** [comment]
Hi again,

I figured out what is going on:
https://github.com/esm-tools/esm_tools/blob/12d6e86e1cace6f5273e2143b68b80e1cd074b96/src/esm_runscripts/filelists.py#L975-L984

Your experiments indeed have all the other fesom namelists, but without a time stamp. The reason for you to have many `namelist.config` with time stamps is because `namelist.config` changes with every run, while the other configs are `identical`, and ESM-Tools avoids copying identical files with identical names. I think this is a reasonable behavior, but let us know what you think.

**Comment by chrisdane** [comment]
Ah well thats awesome, I would vote to keep that behavior. Just a problem of communication I guess.
