### ISSUE TITLE
domain name of levante changed

### ISSUE THREAD

**Issue by vkolatschek** [esm-tools/esm_tools#872]
As of the last maintenance on Levante yesterday, Atos changed the domain name of Levante from atos.local to lvt.dkrz.de (info from Irina Fast from dkrz support). This leads to the following warning when running FESOM1.4:

`WARNING:root:The yaml file for this computer (l20163.lvt.dkrz.de) could not be determined!`
`WARNING:root:Continuing with generic settings...`

With the generic settings, the model seems to run correctly, however automatic resubmission at the end of a job does not work. Can you tell me what I need to change in the esm_tools until you have a permanent solution?

**System:**
 - Supercomputer: Levante
 - Version: esm_tools, version 6.7.1

**Comment by chrisdane** [comment]
Vanessa, for the moment you can apply the change from the pull request. I hope this helps (have to wait until a job-submission comes from the compute node after the initial manual submission from the login node).

@esmtools: Currently, the `run_`-dir will be created using generic settings although the esm_tools do not know the machine. I think this is confusing. I suggest that the esmtools raise an error and stop immediately if they do not recognize the machine (the generic setting is not needed at all). Also, I think it would help if 
```
src/esm_parser/esm_parser.py:    logging.warning("Continuing with generic settings...")
```
would include the word esm_tools or similar so that its immediately clear where this message comes from.

Cheers,
Chris

**Comment by vkolatschek** [comment]
I think it should be:
`'compute_nodes: '^l[A-Za-z0-9]+\.lvt\.dkrz\.de$'`
not
`compute:nodes: '^l[A-Za-z0-9]+\.lvt\.dkrz$'`
Then it works. Thanks!

**Comment by pgierz** [comment]
Why not put your proposed changed into a pull request for the logging message?

**Comment by vkolatschek** [comment]
> Why not put your proposed changed into a pull request for the logging message?

Sorry, I didn't think about it... next time I'll do that directly.

**Comment by pgierz** [comment]
That was more for @chrisdane, but yes. If you see a thing you want to be different, don't be afraid to modify the code and send us a PR 🙂 if it's completely wrong, we will help you figure out where to fix it, and if it's already correct: hooray! You then just saved yourself and all your colleagues from a problem everyone is facing

**Comment by mandresm** [comment]
I think this is solved. If you still have problems, feel free to open the issue again.
