### ISSUE TITLE
Installation error after an authentification failure

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#9]
When I try to insall a model:

> esm_master install-model-version

and then I introduce the wrong password here:

```
Executing commands in this order:
         git clone -b version https://user@gitlab.dkrz.de/modular_esm/model.git model-version
         cd model-version
         ./configure; make
         cd ..
         mkdir -p model-version/bin
         cp model-version/bin/model.x model-version/bin
Cloning into 'model-version'...
Password for 'https://user@gitlab.dkrz.de':
```

I get an expected error:

```
fatal: destination path 'model-version' already exists and is not an empty directory.
./comp-model-version_script.sh: line 84: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
cp: cannot stat `model-version/bin/mpiom.x': No such file or directory
```

However, if I try to install it again I get the same error message without getting to enter the password.

It is possible to solve this problem by manually removing the directory of the model ('> rm -rf model-version'), but could it be useful that this directory is deleted automatically if the authentification fails to avoid this issue?

**Comment by pgierz** [comment]
Sure, you'd need a try/except block around the esm_master part that actually calls the the mini script that is written. There is a way to use `subprocess` module functions to check the error codes of a system call. In any case, we should go through and make sure we aren't using `os.system` anywhere, since that isn't recommended by the Python community.

@dbarbi knows better where exactly that part is actually called.

**Comment by dbarbi** [comment]
I would not automatically remove the folder, as it is well possible the user forgot it exists. But we could have a more sophisticated error message

**Comment by pgierz** [comment]
As of esm_master v4.0.4, the program stops and throws an error as soon as any error is encountered, so this shouldn't happen any more.
