### ISSUE TITLE
ECHAM standalone run crashes in the very beginning

### ISSUE THREAD

**Issue by ghost** [esm-tools/esm_tools#90]
I submitted a one-year (1850-01-01 -- 1851-01-01) ECHAM6.3 T127 time slice run to Mistral with a yaml runscript (esm_tools Python version). The slurm process terminated after 25 min and the resulting run directory is located at: `/mnt/lustre02/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/yaml_run`

As one can see, two `run*` directory are created within the folder. When looking in the `run_18500101-18501231/work/echam.stderr` file, it computes something for January of the first year, but terminates afterwards and jumps to the next year. There, it is not able to find any restart file and crashes (e.g. `run_18510101-18511231/scripts/yaml_run_compute_18510101-18511231_22777808.log` )

My esm_tools directory is located at: `/mnt/lustre02/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/esm_tools`

ECHAM is installed with esm_master in: `/mnt/lustre02/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/echam-6.3.04p1`

The yaml-runscript I am using is: `/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/yaml_run/run_18500101-18501231/scripts/echam_johannes.yaml`

Additionally, esm_tools is apparently looking by default for some JSBACH forcing files at:

> /pool/data/JSBACH/input/r0010/T127/New_Hampshire_LCC/hist_harvest/LUH_harvest_T127_1850.nc
/pool/data/JSBACH/input/r0010/T127/spitfire/a_nd_T127.nc
/pool/data/JSBACH/input/r0010/T127/spitfire/LISOTD_HRMC_V2.2_T127.nc
/pool/data/JSBACH/input/r0010/T127/spitfire/population_density_HYDE_T127.nc

that do not exist and reports theses files as missing files in the very beginning.

**Comment by mandresm** [comment]
Hi @jobo95,

I managed to run the two years with the following `runscript`:

`/pf/a/a270152/my_scripts/echam_johannes.yaml`

The major problem of your runscript seemed to be that the echam section `restart_unit: "years"` was missing, which is important because by default is setup to be "months" and this conflicts with the general configuration in which you have specified year-length runs.

About the missing files, this should not result into run issues as you mentioned they are not needed for non-dynamic vegetation.

Please, let me know if that solved the problem.

**Comment by ghost** [comment]
Hi,
I have no access permissions for `/pf/a/a270152/my_scripts/echam_johannes.yaml`. Can you may adapt the permissions? Or just copy it to another location?

**Comment by mandresm** [comment]
I changed the permissions.

**Comment by ghost** [comment]
> 
> 
> I changed the permissions.

Still not accessible. Maybe just copy it to my scratch folder `/scratch/a/a271093`

**Comment by mandresm** [comment]
Done
