### ISSUE TITLE
Comments for generic maschine file

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#947]
As mentioned in our Monday meeting, it would be good to have some comments for the generic machine file:
https://github.com/esm-tools/esm_tools/blob/release/configs/machines/generic.yaml

So that it can serve as a more self explanatory base for users trying to install models on machines we have no access to.

**Comment by pgierz** [comment]
Additional info which may be of interest, here's CLI bit you can use to create a new configuration from the command line, this could be copied for machines. It is currently for components:

https://github.com/esm-tools/esm_tools/blob/7b7f5091fddf2b4616a3261c13105a7c270f4fb7/src/esm_tools/cli.py#L32-L58

The original PR I had for this also had an example. In retrospect it would have been nice to just have that as a comment in the doc-string instead of having it in two different places: https://github.com/esm-tools/esm_tools/pull/918#issuecomment-1482463237

**Comment by nwieters** [comment]
I have created a first attempt for a more self-explaining machine file by adding comments and placeholders, see commit a080be4.

Please let me know I you have more helpful comments that I can put into this file. For example about the 'hetjob_flag'. Or if there should be more example variables described related to e.g. compiler, libraries, etc.

I am not sure whether the part for 'partition' needs to be setup in this way. Are all of these variables needed: 
`partition: <partition_name>`
`choose_partition:`
and 
`partitions:` ?

**Comment by nwieters** [comment]
I will also look at the documentation and add a section in the cookbook 'Implement a new machine'.

**Comment by mandresm** [comment]
Can you make a Draft Pull-Request (https://github.blog/2019-02-14-introducing-draft-pull-requests/)? That way is typically easier to look at the differences and make suggestions, and it's a feature we are using a lot lately.

> I will also look at the documentation and add a section in the cookbook 'Implement a new machine'.

I think this would need relatively little documentation, specially since the machine template file would contain all the information one needs to setup a new machine, right?
