### ISSUE TITLE
Minor organisation issue in AWICM1 run folder

### ISSUE THREAD

**Issue by mathanase** [esm-tools/esm_tools#952]
@antoniofis10000 just pointed out a minor organisation 'issue' in AWICM1 runs using ESM tools (version 6.21.5, release branch).

The main output file from ECHAM, named something like this:
`{run_name}.01_echam.nc
`is surprisingly not stored in the folder `{run_name}/outdata/echam/`, but rather in  `{run_name}/unknown/`.

See for example in a run on Levante: `/work/ba1264/a270216/NRT/runtime/awicm1_T127L95_4K_T20_24H_20230401_20230430`

Nothing urgent. But we thought it would be good to address this whenever that is possible!

**Comment by mandresm** [comment]
Looking at how the output handling of ECHAM is done I think I have an idea:

https://github.com/esm-tools/esm_tools/blob/279c277dcad608fdbcaab0fb82af0363f0886f31/configs/components/echam/echam.yaml#L713-L716

In essence the logic `[[streams-->STREAM]]` and `[[streamsnc-->STREAM]]_nc` makes a loop over all the elements in the `echam.streams` and `echam.streamsnc`. You can see that the `"[[streamsnc-->STREAM]]_nc": ${general.expid}_${start_date!syear!smonth}.${start_date!sday}_STREAM.nc ` pattern (where `STREAM` is substituted by the element of the `streamsnc` list) coincides with the files missing (`ls unknown/*.nc`):

```
unknown/awicm1_T127L95_4K_T20_24H_20230401_20230430_209904.01_echam.nc
unknown/awicm1_T127L95_4K_T20_24H_20230401_20230430_209904.01_nudg.nc
unknown/awicm1_T127L95_4K_T20_24H_20230401_20230430_209904.01_soilT.nc               
unknown/restart_awicm1_T127L95_4K_T20_24H_20230401_20230430_20990430235640_soilT.nc 
```

So, the problem is that `echam`, `nudg` and `soilT` are not part of the standard `streams` and `streamsnc` defined in the `echam.yaml`:
https://github.com/esm-tools/esm_tools/blob/279c277dcad608fdbcaab0fb82af0363f0886f31/configs/components/echam/echam.yaml#L652-L686

I suggest that @antoniofis10000 modifies his runscript to include the following:
```diff
echam:
    add_streams:
        - nudg
+        - soilT
+    add_streamsnc:
+        - nudg
+        - echam
+        - soilT
```

If that works we can consider adding those to the `echam.yaml`, so that no one else confronts this problem again.

**Comment by antoniofis10000** [comment]
Thanks for the detailed explanation!

I want to add one comment.
echam.nc is a general output but nudg.nc and soilT.nc are specific for our runs.
So the last two should not be included in the echam.yaml I guess

**Comment by mandresm** [comment]
Perfect, thanks! then we will add the echam one only. Let me know if it does the job

**Comment by mandresm** [comment]
Is this issue resolved? Can it be closed?
