### ISSUE TITLE
 not-detected (=generic) hostname should stop immediately

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#959]
**Describe the bug**
If the esm_tools do not detect the hostname at the beginning of a job to model date1, the esm_parser shows a warning like this:
```
WARNING:root:The yaml file for this computer (l40248) could not be determined!
WARNING:root:Continuing with generic settings...
```
and continues the job. At the end of the job, if a subsequent job is about the be submitted to model date2, the same warning is triggered again and, in addition, since the srun command is crap due to the generic setting, srun has this error:
```
sbatch.bin: error: This does not look like a batch script.  The first
sbatch.bin: error: line must start with #! followed by the path to an interpreter.
sbatch.bin: error: For instance: #!/bin/sh
```
i.e., the job to model date2 is not submitted. After this the esm_runscripts process continues so that the job to model date1 ends successfully.

Does it? How can I know that the job to model date1 ended successfully? Maybe its flawed due to the generic setting? Maybe a default forcing file was used due to the generic setting so that the model run successfully finished but with a forcing file that I did not want to use. 

**Expected behavior**
I think the esm_parser should not raise a warning but an error at the beginning of the job to model date1. Ideally in a way so that 
```
computer:
    mail_type: "FAIL"
    mail_user: "<mymail>
```
is triggered.

Thanks and cheers,
Chris

**Comment by mandresm** [comment]
Hi @chrisdane,

I am not sure I am understanding the issue here, so please, feel free to further comment on this reply.

As the warning says, the problem here is that the machine could not be identified (the hostname does not coincide with any of the patterns in `all_machines.yaml`). Then, instead of loading the machine file that should be loading, it's loading the `generic.yaml` which shouldn't be used to launch any simulation, since it contains all shorts of dummy variables. This of course results into a `srun` command that is "crap".

This feature was developed by an advance user who wanted to develop locally in his laptop and didn't need to be launching simulations but just running dry tests (`check`). This functionality has proven very powerful to us, the development team, and to other advance users, so I doubt we would be getting rid of it.

However, I'm very interested in knowing in which way was all this confusing to you, was the message of ESM-Tools about the generic file not clear? Was it not visible enough? Can you think of an alternative solution that would both satisfy your needs without removing the functionality?

One option that comes to my mind, is that at the time of launching a real simulation, ESM-Tools could through an error, but would still allow you to run check runs.

**Comment by chrisdane** [comment]
Yes please keep this functionality. 

I just want to make sure that the job that shows the warning on top of the log file but continues afterwards and finishes without error is ok and not potentially flawed due to any option set by the generic config (e.g. `/work/ab1095/a270073/out/awicm-1.0-recom/sofia/antwater/log/antwater_awicm_compute_19350101-19351231_5263822.log`).

**Comment by mandresm** [comment]
> I just want to make sure that the job that shows the warning on top of the log file but continues afterwards and finishes without error is ok and not potentially flawed due to any option set by the generic config 

I'm not understanding this sentence. I've look into the log and that's bad. The simulation should crash in this point, because the `general.yaml` contains only dummy environment variables, and you need the ones defined in `levante.yaml`. Is that what you mean?

I'm puzzled about the fact that levante is not recognised by your ESM-Tools, but I guess you know why this happens (an old version of ESM-Tools with the old name pattern in `all_machines.yaml` correct?). Am I understanding correctly that this issue is not about fixing that problem, but on catching with an error that the `generic.yaml` shouldn't be used for actual simulations?

**Comment by chrisdane** [comment]
That the levante node was not recognized in this particular case was a hick-up on the machine. All other runs work fine on levante.


> The simulation should crash in this point, because the general.yaml contains only dummy environment variables, and you need the ones defined in levante.yaml. Is that what you mean?

> Am I understanding correctly that this issue is not about fixing that problem, but on catching with an error that the generic.yaml shouldn't be used for actual simulations?

Yes and yes.

**Comment by mandresm** [comment]
Okay, thanks. I think what I'll do then is to trigger an error during runtime for the `generic.yaml`. Thanks for this bug report!
